name: CI
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build contracts
        id: build
        continue-on-error: true
        run: npm run compile
      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
      - name: "Add build result (success)"
        if: steps.build.outcome == 'success'
        run: |
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      - name: "Add build result (failed)"
        if: steps.build.outcome == 'failure'
        run: |
          echo "❌ Failed" >> $GITHUB_STEP_SUMMARY
  test:
    name: test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test contracts
        id: run_tests
        continue-on-error: true
        run: |
          echo "test_output=$(npm run --silent test)\n" >> $GITHUB_OUTPUT
      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "${{steps.run_tests.outputs.test_output}}"
      - name: "Add test result (success)"
        if: steps.run_tests.outcome == 'success'
        run: |
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
      - name: "Add test result (failed)"
        if: steps.run_tests.outcome == 'failure'
        run: |
          echo "❌ Failed" >> $GITHUB_STEP_SUMMARY
